# Set the base image to Ubuntu
FROM node:slim

# File Author / Maintainer
MAINTAINER Gabriel Malet

# Install PM2
RUN npm install -g pm2

# Define working directory
WORKDIR /src

# Translation (fr)
COPY p.json /src/gop-server/pokemons.json

EXPOSE 3000

# Run app
CMD pm2 start --no-daemon /src/gop-server/processes.dev.json